import MainNavbar from "@/components/navbar/main-navbar";
import "./globals.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavbar />
        
        {children}
      </body>
    </html>
  );
}
