import MainNavbar from "@/components/navbar/main-navbar";
import "./globals.css";

import { Nunito } from "next/font/google";
// import { SourGummy } from "next/font/google";
const nunito = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"], 
  subsets: ["latin"], 
  display:"swap"
});


// const sourGummy = SourGummy({
//   weight: ["200", "300", "400", "500", "600", "700", "800", "900"], 
//   subsets: ["latin"], 
//     display:"swap"
// });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavbar />
        
        {children}
      </body>
    </html>
  );
}
